[tool.poetry]
name = "clip-dk"
version = "0.1.0"
description = ""
authors = ["Charles Parker <charles.parker@mdpanel.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
