# Use the official Label Studio image as a base
FROM heartexlabs/label-studio:latest

# Expose the port that Label Studio runs on
EXPOSE 8080

# Define the entrypoint for Cloud Run
# CMD ["label-studio","-db" ,"postgresql"]
CMD ["label-studio"]
